Briareos\NodejsBundle\Entity\NodejsPresence:
    type: entity
    table: nodejs__presence
    repositoryClass: Briareos\NodejsBundle\Entity\NodejsPresenceRepository
    fields:
        authToken:
            type: string
            length: 255
            id: true
        seenAt:
            type: datetime
    oneToOne:
        subject:
            targetEntity: NodejsSubjectInterface
            joinColumn:
                name: subject_id
                referencedColumnName: id
                onDelete: CASCADE
    lifecycleCallbacks: {  }
