parameters:
    nodejs.dispatcher.class: Briareos\NodejsBundle\Nodejs\Dispatcher
    nodejs.twig.extension.class: Briareos\NodejsBundle\Twig\Extension\Nodejs
    nodejs.authenticator.class: Briareos\NodejsBundle\Nodejs\Authenticator
    nodejs.authenticator.entity_class: Briareos\NodejsBundle\Entity\NodejsPresence
    nodejs.login_listener.class: Briareos\NodejsBundle\Listener\LoginListener

services:
    nodejs.dispatcher:
        class: %nodejs.dispatcher.class%
        arguments:
            - %nodejs.dispatcher.secure%
            - %nodejs.dispatcher.host%
            - %nodejs.dispatcher.port%
            - %nodejs.dispatcher.connect_timeout%
            - %nodejs.dispatcher.resource%
            - %nodejs.dispatcher.service_key%
    nodejs.twig.extension:
        class: %nodejs.twig.extension.class%
        arguments: [ @nodejs.dispatcher, @nodejs.authenticator ]
        tags:
            - { name: twig.extension }
    nodejs.authenticator:
        class: %nodejs.authenticator.class%
        arguments:
            - @doctrine.orm.default_entity_manager
            - %nodejs.authenticator.entity_class%
            - %nodejs.authenticator.lifetime%
    nodejs.login_listener:
        class: %nodejs.login_listener.class%
        arguments: [ @security.context, @nodejs.authenticator, @request ]
        scope: request
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
